image: r-base

pages:
  stage: deploy
  script:
  - apt-get update
  - apt-get -y install python3 
  - apt-get -y install python3-pip 
  - apt-get -y install python3-numpy
  - apt-get -y install python3-matplotlib
  - apt-get -y install python3-pandas
  - apt-get -y install python3-tk
  - wget "https://github.com/jgm/pandoc/releases/download/2.9.1/pandoc-2.9.1-1-amd64.deb"
  - dpkg -i pandoc-2.9.1-1-amd64.deb
  - wget -qO- "https://yihui.name/gh/tinytex/tools/install-unx.sh" | sh
  - Rscript -e "install.packages('knitr')"
  - Rscript -e "install.packages('rmarkdown')"
  - Rscript -e "install.packages('reticulate')"
  - make
  - mkdir .public
  - cp -r *.Rmd *.html *.ipynb *.pdf .public
  - rm .public/header.html
  - mv .public public

  artifacts:
    paths:
    - public
  only:
  - master
